### PR TITLE
Add eslint config & fix styling issues

### LINKED ISSUE #9: Improve Codacy rating!
Hello there fellow member.

See that Codacy badge and with a grade A. If you click on it it'll show you some stats about the project. Do you see thoose 52 code style issues. Yeah it's bad. So i propose to remove most of them. All you have to do is look at each line and see what's the mistake aand fix it.

Happy Refactoring.

### PR DESCRIPTION
**Pull request by embiem**
fixes #9

### CODE REVIEW

**Comment by embiem** [comment]
As there was no style guide and no es-lint setup, I used the standard es-lint style. We could certainly modify this style to fit this repo's preferences. E.g. semicolons yes or no is always a very hot topic :-P

**Comment by MatejMecka** [comment]
Thanks mate. Yeah Definetly sticking to the standard eslint

**Comment by MatejMecka** [comment]
Also congrats on completing the Hacktoberfest challenge @mBeierl

**Comment by embiem** [comment]
Thanks :) It's very cool. Would've not found your repo otherwise. I like the bot, as I wanted to create a Slack bot myself for quite some time and have done things with the Google Assistant in the past. I may stick around here and add some commands ;-)

**Pull request merged**
